# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

glm_coefs <- function(y1, X1, w1, epsilon) {
    .Call('_EMandMMPackage_glm_coefs', PACKAGE = 'EMandMMPackage', y1, X1, w1, epsilon)
}

singleEM0_C <- function(K, params, x1, epsilon) {
    .Call('_EMandMMPackage_singleEM0_C', PACKAGE = 'EMandMMPackage', K, params, x1, epsilon)
}

singleEM_C <- function(K, params, x1, epsilon) {
    .Call('_EMandMMPackage_singleEM_C', PACKAGE = 'EMandMMPackage', K, params, x1, epsilon)
}

